# Generated by Django 3.2.9 on 2021-11-15 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_todos', to='auth.user', verbose_name='creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='made_todos', to='auth.user', verbose_name='maker'),
            preserve_default=False,
        ),
    ]
