# Generated by Django 3.2.9 on 2021-11-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211115_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_todos', to='core.person', verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='made_todos', to='core.person', verbose_name='maker'),
        ),
    ]
